// Custom theme presets beyond just accent colors
export const THEME_PRESETS = {
  // Ocean Blue Theme
  oceanBlue: {
    id: 'oceanBlue',
    name: 'Ocean Blue',
    description: 'Deep blue ocean vibes',
    colors: {
      primary: '#0077BE',
      accent: '#00A0E4',
      accent2: '#40C4FF',
      accentLight: '#E6F7FF',
      background: '#F8FCFF',
      surface: '#FFFFFF',
      surfaceElevated: '#F0F9FF',
      border: '#E1F0F9',
      textPrimary: '#1A365D',
      textSecondary: '#4A90A4',
      success: '#059669',
      warning: '#D97706',
      destructive: '#DC2626',
    },
  },

  // Simple Blue Theme
  simpleBlue: {
    id: 'simpleBlue',
    name: 'Simple Blue',
    description: 'Clean, minimal blue',
    colors: {
      primary: '#2563EB',
      accent: '#3B82F6',
      accent2: '#60A5FA',
      accentLight: '#DBEAFE',
      background: '#FFFFFF',
      surface: '#F8FAFC',
      surfaceElevated: '#F1F5F9',
      border: '#E2E8F0',
      textPrimary: '#0F172A',
      textSecondary: '#64748B',
      success: '#10B981',
      warning: '#F59E0B',
      destructive: '#EF4444',
    },
  },

  // Simple Green Theme
  simpleGreen: {
    id: 'simpleGreen',
    name: 'Simple Green',
    description: 'Clean, minimal green',
    colors: {
      primary: '#16A34A',
      accent: '#22C55E',
      accent2: '#4ADE80',
      accentLight: '#DCFCE7',
      background: '#FFFFFF',
      surface: '#F8FAFC',
      surfaceElevated: '#F1F5F9',
      border: '#E2E8F0',
      textPrimary: '#0F172A',
      textSecondary: '#64748B',
      success: '#10B981',
      warning: '#F59E0B',
      destructive: '#EF4444',
    },
  },

  // Simple Purple Theme
  simplePurple: {
    id: 'simplePurple',
    name: 'Simple Purple',
    description: 'Clean, minimal purple',
    colors: {
      primary: '#7C3AED',
      accent: '#8B5CF6',
      accent2: '#A78BFA',
      accentLight: '#EDE9FE',
      background: '#FFFFFF',
      surface: '#F8FAFC',
      surfaceElevated: '#F1F5F9',
      border: '#E2E8F0',
      textPrimary: '#0F172A',
      textSecondary: '#64748B',
      success: '#10B981',
      warning: '#F59E0B',
      destructive: '#EF4444',
    },
  },

  // Simple Red Theme
  simpleRed: {
    id: 'simpleRed',
    name: 'Simple Red',
    description: 'Clean, minimal red',
    colors: {
      primary: '#DC2626',
      accent: '#EF4444',
      accent2: '#F87171',
      accentLight: '#FEE2E2',
      background: '#FFFFFF',
      surface: '#F8FAFC',
      surfaceElevated: '#F1F5F9',
      border: '#E2E8F0',
      textPrimary: '#0F172A',
      textSecondary: '#64748B',
      success: '#10B981',
      warning: '#F59E0B',
      destructive: '#EF4444',
    },
  },

  // Simple Orange Theme
  simpleOrange: {
    id: 'simpleOrange',
    name: 'Simple Orange',
    description: 'Clean, minimal orange',
    colors: {
      primary: '#EA580C',
      accent: '#F97316',
      accent2: '#FB923C',
      accentLight: '#FED7AA',
      background: '#FFFFFF',
      surface: '#F8FAFC',
      surfaceElevated: '#F1F5F9',
      border: '#E2E8F0',
      textPrimary: '#0F172A',
      textSecondary: '#64748B',
      success: '#10B981',
      warning: '#F59E0B',
      destructive: '#EF4444',
    },
  },

  // Simple Teal Theme
  simpleTeal: {
    id: 'simpleTeal',
    name: 'Simple Teal',
    description: 'Clean, minimal teal',
    colors: {
      primary: '#0D9488',
      accent: '#14B8A6',
      accent2: '#5EEAD4',
      accentLight: '#CCFBF1',
      background: '#FFFFFF',
      surface: '#F8FAFC',
      surfaceElevated: '#F1F5F9',
      border: '#E2E8F0',
      textPrimary: '#0F172A',
      textSecondary: '#64748B',
      success: '#10B981',
      warning: '#F59E0B',
      destructive: '#EF4444',
    },
  },

  // Simple Yellow Theme
  simpleYellow: {
    id: 'simpleYellow',
    name: 'Simple Yellow',
    description: 'Clean, minimal yellow',
    colors: {
      primary: '#CA8A04',
      accent: '#EAB308',
      accent2: '#FDE047',
      accentLight: '#FEF3C7',
      background: '#FFFFFF',
      surface: '#F8FAFC',
      surfaceElevated: '#F1F5F9',
      border: '#E2E8F0',
      textPrimary: '#0F172A',
      textSecondary: '#64748B',
      success: '#10B981',
      warning: '#F59E0B',
      destructive: '#EF4444',
    },
  },

  // Simple Pink Theme
  simplePink: {
    id: 'simplePink',
    name: 'Simple Pink',
    description: 'Clean, minimal pink',
    colors: {
      primary: '#DB2777',
      accent: '#EC4899',
      accent2: '#F472B6',
      accentLight: '#FCE7F3',
      background: '#FFFFFF',
      surface: '#F8FAFC',
      surfaceElevated: '#F1F5F9',
      border: '#E2E8F0',
      textPrimary: '#0F172A',
      textSecondary: '#64748B',
      success: '#10B981',
      warning: '#F59E0B',
      destructive: '#EF4444',
    },
  },

  // Simple Indigo Theme
  simpleIndigo: {
    id: 'simpleIndigo',
    name: 'Simple Indigo',
    description: 'Clean, minimal indigo',
    colors: {
      primary: '#4338CA',
      accent: '#6366F1',
      accent2: '#818CF8',
      accentLight: '#E0E7FF',
      background: '#FFFFFF',
      surface: '#F8FAFC',
      surfaceElevated: '#F1F5F9',
      border: '#E2E8F0',
      textPrimary: '#0F172A',
      textSecondary: '#64748B',
      success: '#10B981',
      warning: '#F59E0B',
      destructive: '#EF4444',
    },
  },

  // Simple Gray Theme
  simpleGray: {
    id: 'simpleGray',
    name: 'Simple Gray',
    description: 'Clean, minimal gray',
    colors: {
      primary: '#374151',
      accent: '#6B7280',
      accent2: '#9CA3AF',
      accentLight: '#F3F4F6',
      background: '#FFFFFF',
      surface: '#F8FAFC',
      surfaceElevated: '#F1F5F9',
      border: '#E2E8F0',
      textPrimary: '#0F172A',
      textSecondary: '#64748B',
      success: '#10B981',
      warning: '#F59E0B',
      destructive: '#EF4444',
    },
  },

  // Forest Green Theme
  forestGreen: {
    id: 'forestGreen',
    name: 'Forest Green',
    description: 'Natural forest colors',
    colors: {
      primary: '#16A085',
      accent: '#27AE60',
      accent2: '#4CAF50',
      accentLight: '#E8F8F5',
      background: '#F7FCFA',
      surface: '#FFFFFF',
      surfaceElevated: '#F0FAF7',
      border: '#D5E8E1',
      textPrimary: '#1B4332',
      textSecondary: '#52796F',
      success: '#059669',
      warning: '#D97706',
      destructive: '#DC2626',
    },
  },

  // Sunset Orange Theme
  sunsetOrange: {
    id: 'sunsetOrange',
    name: 'Sunset Orange',
    description: 'Warm sunset colors',
    colors: {
      primary: '#E67E22',
      accent: '#FF6B35',
      accent2: '#FF8A50',
      accentLight: '#FFF2E6',
      background: '#FFFBF7',
      surface: '#FFFFFF',
      surfaceElevated: '#FFF7ED',
      border: '#F4E4D6',
      textPrimary: '#7C2D12',
      textSecondary: '#C2410C',
      success: '#059669',
      warning: '#D97706',
      destructive: '#DC2626',
    },
  },

  // Purple Dream Theme
  purpleDream: {
    id: 'purpleDream',
    name: 'Purple Dream',
    description: 'Royal purple elegance',
    colors: {
      primary: '#8B5CF6',
      accent: '#A855F7',
      accent2: '#C084FC',
      accentLight: '#F3E8FF',
      background: '#FEFCFF',
      surface: '#FFFFFF',
      surfaceElevated: '#FAF5FF',
      border: '#E9D5FF',
      textPrimary: '#581C87',
      textSecondary: '#7C3AED',
      success: '#059669',
      warning: '#D97706',
      destructive: '#DC2626',
    },
  },

  // Rose Pink Theme
  rosePink: {
    id: 'rosePink',
    name: 'Rose Pink',
    description: 'Soft rose garden',
    colors: {
      primary: '#E91E63',
      accent: '#F06292',
      accent2: '#F8BBD9',
      accentLight: '#FCE4EC',
      background: '#FFFBFC',
      surface: '#FFFFFF',
      surfaceElevated: '#FDF2F8',
      border: '#F8D7DA',
      textPrimary: '#880E4F',
      textSecondary: '#AD1457',
      success: '#059669',
      warning: '#D97706',
      destructive: '#DC2626',
    },
  },

  // Crimson Red Theme
  crimsonRed: {
    id: 'crimsonRed',
    name: 'Crimson Red',
    description: 'Bold crimson energy',
    colors: {
      primary: '#DC143C',
      accent: '#FF1744',
      accent2: '#FF5983',
      accentLight: '#FFEBEE',
      background: '#FFFAFA',
      surface: '#FFFFFF',
      surfaceElevated: '#FFF5F5',
      border: '#FFCDD2',
      textPrimary: '#B71C1C',
      textSecondary: '#D32F2F',
      success: '#059669',
      warning: '#D97706',
      destructive: '#DC2626',
    },
  },

  // Lime Green Theme
  limeGreen: {
    id: 'limeGreen',
    name: 'Lime Green',
    description: 'Fresh lime vibrancy',
    colors: {
      primary: '#8BC34A',
      accent: '#CDDC39',
      accent2: '#FFEB3B',
      accentLight: '#F9FBE7',
      background: '#FCFFF5',
      surface: '#FFFFFF',
      surfaceElevated: '#F9FBE7',
      border: '#DCEDC8',
      textPrimary: '#33691E',
      textSecondary: '#689F38',
      success: '#059669',
      warning: '#D97706',
      destructive: '#DC2626',
    },
  },

  // Sky Blue Theme
  skyBlue: {
    id: 'skyBlue',
    name: 'Sky Blue',
    description: 'Clear sky serenity',
    colors: {
      primary: '#03A9F4',
      accent: '#00BCD4',
      accent2: '#4FC3F7',
      accentLight: '#E1F5FE',
      background: '#F1F8FF',
      surface: '#FFFFFF',
      surfaceElevated: '#E3F2FD',
      border: '#B3E5FC',
      textPrimary: '#0D47A1',
      textSecondary: '#1976D2',
      success: '#059669',
      warning: '#D97706',
      destructive: '#DC2626',
    },
  },

  // Midnight Dark Theme
  midnightDark: {
    id: 'midnightDark',
    name: 'Midnight Dark',
    description: 'Deep dark theme',
    isDark: true,
    colors: {
      primary: '#3B82F6',
      accent: '#60A5FA',
      accent2: '#93C5FD',
      accentLight: '#1E3A8A',
      background: '#0F172A',
      surface: '#1E293B',
      surfaceElevated: '#334155',
      border: '#334155',
      textPrimary: '#F1F5F9',
      textSecondary: '#94A3B8',
      success: '#10B981',
      warning: '#F59E0B',
      destructive: '#EF4444',
    },
  },

  // Simple Blue Dark Theme
  simpleBlueDark: {
    id: 'simpleBlueDark',
    name: 'Simple Blue Dark',
    description: 'Clean, minimal blue dark',
    isDark: true,
    colors: {
      primary: '#3B82F6',
      accent: '#60A5FA',
      accent2: '#93C5FD',
      accentLight: '#1E3A8A',
      background: '#0F172A',
      surface: '#1E293B',
      surfaceElevated: '#334155',
      border: '#475569',
      textPrimary: '#F1F5F9',
      textSecondary: '#94A3B8',
      success: '#10B981',
      warning: '#F59E0B',
      destructive: '#EF4444',
    },
  },

  // Simple Green Dark Theme
  simpleGreenDark: {
    id: 'simpleGreenDark',
    name: 'Simple Green Dark',
    description: 'Clean, minimal green dark',
    isDark: true,
    colors: {
      primary: '#22C55E',
      accent: '#4ADE80',
      accent2: '#86EFAC',
      accentLight: '#14532D',
      background: '#0F1A0F',
      surface: '#1B2F1B',
      surfaceElevated: '#2D4A2D',
      border: '#365A36',
      textPrimary: '#F0FDF4',
      textSecondary: '#86EFAC',
      success: '#10B981',
      warning: '#F59E0B',
      destructive: '#EF4444',
    },
  },

  // Simple Purple Dark Theme
  simplePurpleDark: {
    id: 'simplePurpleDark',
    name: 'Simple Purple Dark',
    description: 'Clean, minimal purple dark',
    isDark: true,
    colors: {
      primary: '#8B5CF6',
      accent: '#A78BFA',
      accent2: '#C4B5FD',
      accentLight: '#4C1D95',
      background: '#1E1B3A',
      surface: '#312E5A',
      surfaceElevated: '#4A4570',
      border: '#5B5285',
      textPrimary: '#F5F3FF',
      textSecondary: '#C4B5FD',
      success: '#10B981',
      warning: '#F59E0B',
      destructive: '#EF4444',
    },
  },

  // Simple Red Dark Theme
  simpleRedDark: {
    id: 'simpleRedDark',
    name: 'Simple Red Dark',
    description: 'Clean, minimal red dark',
    isDark: true,
    colors: {
      primary: '#EF4444',
      accent: '#F87171',
      accent2: '#FCA5A5',
      accentLight: '#7F1D1D',
      background: '#1F0F0F',
      surface: '#3A1E1E',
      surfaceElevated: '#4F2B2B',
      border: '#5F3535',
      textPrimary: '#FEF2F2',
      textSecondary: '#FCA5A5',
      success: '#10B981',
      warning: '#F59E0B',
      destructive: '#EF4444',
    },
  },

  // Simple Orange Dark Theme
  simpleOrangeDark: {
    id: 'simpleOrangeDark',
    name: 'Simple Orange Dark',
    description: 'Clean, minimal orange dark',
    isDark: true,
    colors: {
      primary: '#F97316',
      accent: '#FB923C',
      accent2: '#FDBA74',
      accentLight: '#9A3412',
      background: '#1F1709',
      surface: '#3A2E15',
      surfaceElevated: '#4F3A1F',
      border: '#5F4527',
      textPrimary: '#FFFBEB',
      textSecondary: '#FDBA74',
      success: '#10B981',
      warning: '#F59E0B',
      destructive: '#EF4444',
    },
  },

  // Simple Teal Dark Theme
  simpleTealDark: {
    id: 'simpleTealDark',
    name: 'Simple Teal Dark',
    description: 'Clean, minimal teal dark',
    isDark: true,
    colors: {
      primary: '#14B8A6',
      accent: '#5EEAD4',
      accent2: '#99F6E4',
      accentLight: '#134E4A',
      background: '#0F1F1C',
      surface: '#1B3330',
      surfaceElevated: '#2D4744',
      border: '#3D5653',
      textPrimary: '#F0FDFA',
      textSecondary: '#99F6E4',
      success: '#10B981',
      warning: '#F59E0B',
      destructive: '#EF4444',
    },
  },

  // Simple Yellow Dark Theme
  simpleYellowDark: {
    id: 'simpleYellowDark',
    name: 'Simple Yellow Dark',
    description: 'Clean, minimal yellow dark',
    isDark: true,
    colors: {
      primary: '#EAB308',
      accent: '#FDE047',
      accent2: '#FEF08A',
      accentLight: '#713F12',
      background: '#1F1F0A',
      surface: '#333316',
      surfaceElevated: '#474721',
      border: '#57572A',
      textPrimary: '#FEFCE8',
      textSecondary: '#FEF08A',
      success: '#10B981',
      warning: '#F59E0B',
      destructive: '#EF4444',
    },
  },

  // Simple Pink Dark Theme
  simplePinkDark: {
    id: 'simplePinkDark',
    name: 'Simple Pink Dark',
    description: 'Clean, minimal pink dark',
    isDark: true,
    colors: {
      primary: '#EC4899',
      accent: '#F472B6',
      accent2: '#F9A8D4',
      accentLight: '#831843',
      background: '#1F0F1A',
      surface: '#3A1E30',
      surfaceElevated: '#4F2B42',
      border: '#5F3650',
      textPrimary: '#FDF2F8',
      textSecondary: '#F9A8D4',
      success: '#10B981',
      warning: '#F59E0B',
      destructive: '#EF4444',
    },
  },

  // Simple Indigo Dark Theme
  simpleIndigoDark: {
    id: 'simpleIndigoDark',
    name: 'Simple Indigo Dark',
    description: 'Clean, minimal indigo dark',
    isDark: true,
    colors: {
      primary: '#6366F1',
      accent: '#818CF8',
      accent2: '#A5B4FC',
      accentLight: '#312E81',
      background: '#1E1E3F',
      surface: '#312E5A',
      surfaceElevated: '#4338CA',
      border: '#4F46E5',
      textPrimary: '#E0E7FF',
      textSecondary: '#A5B4FC',
      success: '#10B981',
      warning: '#F59E0B',
      destructive: '#EF4444',
    },
  },

  // Simple Gray Dark Theme
  simpleGrayDark: {
    id: 'simpleGrayDark',
    name: 'Simple Gray Dark',
    description: 'Clean, minimal gray dark',
    isDark: true,
    colors: {
      primary: '#6B7280',
      accent: '#9CA3AF',
      accent2: '#D1D5DB',
      accentLight: '#374151',
      background: '#111827',
      surface: '#1F2937',
      surfaceElevated: '#374151',
      border: '#4B5563',
      textPrimary: '#F9FAFB',
      textSecondary: '#D1D5DB',
      success: '#10B981',
      warning: '#F59E0B',
      destructive: '#EF4444',
    },
  },

  // Chocolate Dark Theme
  chocolateDark: {
    id: 'chocolateDark',
    name: 'Chocolate Dark',
    description: 'Rich chocolate brown',
    isDark: true,
    colors: {
      primary: '#D2691E',
      accent: '#FF8C42',
      accent2: '#FFB74D',
      accentLight: '#8B4513',
      background: '#2D1810',
      surface: '#3E2723',
      surfaceElevated: '#5D4037',
      border: '#5D4037',
      textPrimary: '#EFEBE9',
      textSecondary: '#BCAAA4',
      success: '#4CAF50',
      warning: '#FF9800',
      destructive: '#F44336',
    },
  },

  // Matrix Green Dark Theme
  matrixGreen: {
    id: 'matrixGreen',
    name: 'Matrix Green',
    description: 'Hacker green matrix',
    isDark: true,
    colors: {
      primary: '#00FF41',
      accent: '#39FF14',
      accent2: '#76FF03',
      accentLight: '#1B5E20',
      background: '#0D1B0D',
      surface: '#1A2F1A',
      surfaceElevated: '#2E7D2E',
      border: '#2E7D2E',
      textPrimary: '#E8F5E8',
      textSecondary: '#81C784',
      success: '#4CAF50',
      warning: '#FF9800',
      destructive: '#F44336',
    },
  },

  // Cyber Purple Dark Theme
  cyberPurple: {
    id: 'cyberPurple',
    name: 'Cyber Purple',
    description: 'Cyberpunk purple glow',
    isDark: true,
    colors: {
      primary: '#9C27B0',
      accent: '#E91E63',
      accent2: '#FF4081',
      accentLight: '#4A148C',
      background: '#1A0E2E',
      surface: '#2D1B3D',
      surfaceElevated: '#4A2C5A',
      border: '#6A4C93',
      textPrimary: '#F3E5F5',
      textSecondary: '#CE93D8',
      success: '#4CAF50',
      warning: '#FF9800',
      destructive: '#F44336',
    },
  },

  // Ember Dark Theme
  emberDark: {
    id: 'emberDark',
    name: 'Ember Dark',
    description: 'Glowing ember warmth',
    isDark: true,
    colors: {
      primary: '#FF5722',
      accent: '#FF9800',
      accent2: '#FFC107',
      accentLight: '#BF360C',
      background: '#1C0D00',
      surface: '#3E2723',
      surfaceElevated: '#5D4037',
      border: '#8D6E63',
      textPrimary: '#FFF3E0',
      textSecondary: '#FFCC80',
      success: '#4CAF50',
      warning: '#FF9800',
      destructive: '#F44336',
    },
  },
};

// Get available themes for current mode (light/dark)
export const getAvailableThemes = (isDarkMode) => {
  return Object.values(THEME_PRESETS).filter(theme => 
    isDarkMode ? theme.isDark : !theme.isDark
  );
};

// Get theme by ID
export const getThemeById = (themeId) => {
  return THEME_PRESETS[themeId] || THEME_PRESETS.oceanBlue;
};